version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocyclo

issues:
  exclude-rules:
    - path: "_mock\\.go$"
      linters:
        - gocyclo
    - path: "_test\\.go$"
      linters:
        - gocyclo
    - path: "(^|/)tests/"
      linters:
        - gocyclo

formatters:
  enable:
    - gofmt
    - goimports