
version: '3.8'

services:
  mesh:
    build:
      context: .
    container_name: vechain-mesh
    ports:
      - "8080:8080"  # Mesh API
      - "8669:8669"  # HTTP API (TCP)
      - "11235:11235"  # P2P (TCP)
      - "11235:11235/udp"  # P2P (UDP)
    environment:
      - MODE=${MODE:-online}
      - NETWORK=${NETWORK:-test}
      - PORT=8080
    restart: unless-stopped
    networks:
      - vechain-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  vechain-network:
    driver: bridge
