name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false

      - name: Check modernize (code style)
        run: |
          go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -test ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.1
          args: --timeout=30m --config=.golangci.yml
          only-new-issues: false
          skip-cache: true

  test-unit-coverage:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests with coverage threshold
        run: |
          echo "Coverage is calculated differently from codecov, expect this one to be higher"
          make test-unit-coverage-threshold

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage_filtered.out
          disable_search: true
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: go mod download

      - name: Run full E2E test cycle
        run: make test-e2e-full

  mesh-cli-validation:
    name: Mesh CLI Validation (${{ matrix.env }} - ${{ matrix.validation }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Solo: data + construction
          - env: solo
            validation: data
          - env: solo
            validation: construction
          # Test: data (construction not included since it has to wait for the network to be synced)
          - env: test
            validation: data
          # Main: data only
          - env: main
            validation: data
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: go mod download

      - name: Build mesh-cli Docker image
        run: make mesh-cli-build

      - name: Run mesh-cli ${{ matrix.validation }} validation on ${{ matrix.env }}
        run: make mesh-cli-check-${{ matrix.validation }} ENV=${{ matrix.env }}
